### ISSUE TITLE
Plugin not compatible with current version of Tailwind 1.1.x

### ISSUE THREAD

**Issue by KevinNTH** [hawezo/tailwindcss-theming#5]
I've used the `prefers-scheme` example of `tailwindcss-theming` and downgrade the Tailwind version to `1.1.3` and I get this error because ThemeBuilder is not a function:

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: plugin is not a function
    at /home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/tailwindcss/lib/util/processPlugins.js:49:5
        at Array.forEach (<anonymous>)
	    at _default (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/tailwindcss/lib/util/processPlugins.js:48:11)
	        at /home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/tailwindcss/lib/processTailwindFeatures.js:33:58
		    at LazyResult.run (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:295:14)
		        at LazyResult.asyncTick (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:208:26)
			    at LazyResult.asyncTick (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:221:14)
			        at /home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:213:17

 @ ./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=postcss&scoped=true& 4:14-385 14:3-18:5 15:22-393
  @ ./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=postcss&scoped=true&
   @ ./src/App.vue
    @ ./src/main.ts
     @ multi (webpack)-dev-server/client?http://192.168.0.10:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./src/css/app.css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: plugin is not a function
    at /home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/tailwindcss/lib/util/processPlugins.js:49:5
        at Array.forEach (<anonymous>)
	    at _default (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/tailwindcss/lib/util/processPlugins.js:48:11)
	        at /home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/tailwindcss/lib/processTailwindFeatures.js:33:58
		    at LazyResult.run (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:295:14)
		        at LazyResult.asyncTick (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:208:26)
			    at LazyResult.asyncTick (/home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:221:14)
			        at /home/kevin/web/tailwindcss-theming/examples/prefers-scheme/node_modules/postcss/lib/lazy-result.js:213:17

 @ ./src/css/app.css 4:14-161 14:3-18:5 15:22-169
  @ ./src/main.ts
   @ multi (webpack)-dev-server/client?http://192.168.0.10:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

No type errors found
Version: typescript 3.5.3
Time: 2278ms
```

It should be mentionned at least in the documentation that this is experimental to Tailwind canary version.

**Comment by hawezo** [comment]
Hey, thanks for pointing this out! I added a mention in the docs. My bad! 

Tailwind v1.2 changes the plugin system and allows plugins to have their own configuration, so they can override or extend parts of the configuration. That's what make this plugin work well. Before that, the configuration was a bit odd. 

If you still want to use Tailwind v1.1, you can install [v0.1.4 of this plugin](https://www.npmjs.com/package/tailwindcss-theming/v/0.1.4). But I don't recommend it.

**Comment by KevinNTH** [comment]
Thanks :)

I upgraded to Tailwind v1.2 ;)
